name: PR Title Linter
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

jobs:
  check_title_of_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '[a-zA-Z]+\d:\s\w+\s\w+'

      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.regex-match.outputs.match == '' }}
        with:
          message: |
            Please, current PR name is ${{ steps.regex-match.outputs.match == '' }}, but should be: Homework<number>: Name Surname
