name: PR Title Linter
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

jobs:
  pr_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "[a-zA-Z]+[0-9]: [a-zA-Z]+ [a-zA-Z]+"
          on-failed-regex-fail-action: false
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: true
          on-failed-regex-comment:
            "Please, FIX PR name, but should be ``Homework<number><:> <Name Surname>``"
